In [1]:
%pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

Looking in indexes: https://download.pytorch.org/whl/cu121
Requirement already satisfied: torch in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (2.5.1+cu121)
Requirement already satisfied: torchvision in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (0.20.1+cu121)
Requirement already satisfied: torchaudio in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (2.5.1+cu121)
Requirement already satisfied: filelock in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.24.3)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torch) (4.15.0)
Requirement already satisfied: networkx in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torch) (2025.3.0)
Requirement already satisfied: setuptools in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torch) (82.0.0)
Requirement already satisfied: sympy==1.13.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: numpy in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torchvision) (2.4.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torchvision) (12.1.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from jinja2->torch) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install datasets

Requirement already satisfied: datasets in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (3.6.0)
Requirement already satisfied: filelock in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets) (3.24.3)
Requirement already satisfied: numpy>=1.17 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets) (2.4.2)
Requirement already satisfied: pyarrow>=15.0.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets) (3.0.1)
Requirement already satisfied: requests>=2.32.2 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets) (2.32.5)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets) (1.4.1)
Requirement already satisfied: packaging in c:\users\admin\appdata\roaming\python\python312\site-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.24.0->datasets) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: shellingham in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.24.0->datasets) (1.5.4)
Requirement already satisfied: typer-slim in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.24.0->datasets) (0.24.0)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.32.2->datasets) (2026.1.4)
Requirement already satisfied: colorama in c:\users\admin\appdata\roaming\python\python312\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: anyio in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.12.1)
Requirement already satisfied: httpcore==1.* in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: typer>=0.24.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from typer-slim->huggingface-hub>=0.24.0->datasets) (0.24.0)
Requirement already satisfied: click>=8.2.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.24.0->datasets) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.24.0->datasets) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.24.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.24.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.24.0->datasets) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.24.0->datasets) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:

!pip install pandas numpy scikit-learn scipy tqdm
!pip install torch torchvision torchaudio
!pip install transformers datasets
!pip install matplotlib seaborn
!pip install textattack
!pip install nltk

# --- Optional: If you get errors with textattack, install these specific versions ---
# !pip install tensorflow  # Only needed if you use specific Universal Sentence Encoder constraints
# !pip install editdistance

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.0.1)
Requirement already satisfied: numpy in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (2.4.2)
Requirement already satisfied: scikit-learn in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (1.8.0)
Requirement already satisfied: scipy in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (1.17.0)
Requirement already satisfied: tqdm in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2025.3)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: colorama in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: six>=1.5 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: torch in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (2.10.0)
Requirement already satisfied: torchvision in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (0.25.0)
Requirement already satisfied: torchaudio in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (2.10.0)
Requirement already satisfied: filelock in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from torch) (3.24.2)
Requirement already satisfied: typing-extensions>=4.10.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from torch) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from torch) (2025.10.0)
Requirement already satisfied: setuptools in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from torch) (82.0.0)
Requirement already satisfied: numpy in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from torchvision) (2.4.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from torchvision) (12.1.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from jinja2->torch) (3.0.3)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: transformers in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (4.57.6)
Requirement already satisfied: datasets in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (4.5.0)
Requirement already satisfied: filelock in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from transformers) (3.24.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from transformers) (0.36.2)
Requirement already satisfied: numpy>=1.17 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from transformers) (2.4.2)
Requirement already satisfied: packaging>=20.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from transformers) (2026.1.15)
Requirement already satisfied: requests in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from transformers) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: pyarrow>=21.0.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from datasets) (0.4.0)
Requirement already satisfied: pandas in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from datasets) (3.0.1)
Requirement already satisfied: httpx<1.0.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from datasets) (0.70.18)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: anyio in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: httpcore==1.* in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests->transformers) (2.6.3)
Requirement already satisfied: colorama in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.10.8)
Requirement already satisfied: seaborn in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (2.4.2)
Requirement already satisfied: packaging>=20.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from seaborn) (3.0.1)
Requirement already satisfied: tzdata in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: textattack in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (0.3.10)
Requirement already satisfied: bert-score>=0.3.5 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from textattack) (0.3.13)
Requirement already satisfied: editdistance in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from textattack) (0.8.1)
Requirement already satisfied: flair in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from textattack) (0.15.1)
Requirement already satisfied: filelock in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from textattack) (3.24.2)
Requirement already satisfied: language-tool-python in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from textattack) (3.2.2)
Requirement already satisfied: lemminflect in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from textattack) (0.2.3)
Requirement already satisfied: lru-dict in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from textattack) (1.4.1)
Requirement already satisfied: datasets>=2.4.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from textattack) (4.5.0)
Requirement already satisfied: nltk in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from textattack) (3.9.2)
Requirement already satisfied: numpy>=1.21.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from textattack) (2.4.2)

In [4]:
!pip install datasets pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: datasets in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (4.5.0)
Requirement already satisfied: pandas in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.0.1)
Requirement already satisfied: filelock in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from datasets) (3.24.2)
Requirement already satisfied: numpy>=1.17 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from datasets) (2.4.2)
Requirement already satisfied: pyarrow>=21.0.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from datasets) (0.4.0)
Requirement already satisfied: requests>=2.32.2 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from datasets) (2.32.5)
Requirement already satisfied: httpx<1.0.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from datasets) (0.70.18)
Requirement already satisfied: fsspec<=2025.10.0,>=2023.1.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2025.10.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from datasets) (0.36.2)
Requirement already satisfied: packaging in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: anyio in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: httpcore==1.* in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: colorama in C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)

In [5]:
%pip install torch torchvision torchaudio

Requirement already satisfied: torch in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (2.5.1+cu121)
Requirement already satisfied: torchvision in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (0.20.1+cu121)
Requirement already satisfied: torchaudio in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (2.5.1+cu121)
Requirement already satisfied: filelock in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.24.3)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torch) (4.15.0)
Requirement already satisfied: networkx in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torch) (2025.3.0)
Requirement already satisfied: setuptools in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torch) (82.0.0)
Requirement already satisfied: sympy==1.13.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: numpy in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torchvision) (2.4.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torchvision) (12.1.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from jinja2->torch) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
%pip install transformers datasets scikit-learn

Requirement already satisfied: transformers in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (5.2.0)
Requirement already satisfied: datasets in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (3.6.0)
Requirement already satisfied: scikit-learn in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (1.8.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from transformers) (1.4.1)
Requirement already satisfied: numpy>=1.17 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from transformers) (2.4.2)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from transformers) (2026.2.19)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets) (3.24.3)
Requirement already satisfied: pyarrow>=15.0.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets) (3.0.1)
Requirement already satisfied: requests>=2.32.2 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets) (2.32.5)
Requirement already satisfied: xxhash in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: scipy>=1.10.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: shellingham in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.32.2->datasets) (2026.1.4)
Requirement already satisfied: colorama in c:\users\admin\appdata\roaming\python\python312\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: typer>=0.24.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from typer-slim->transformers) (0.24.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: anyio in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: httpcore==1.* in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from typer>=0.24.0->typer-slim->transformers) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from typer>=0.24.0->typer-slim->transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from typer>=0.24.0->typer-slim->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
%pip install datasets==3.6.0

Requirement already satisfied: datasets==3.6.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (3.6.0)
Requirement already satisfied: filelock in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets==3.6.0) (3.24.3)
Requirement already satisfied: numpy>=1.17 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets==3.6.0) (2.4.2)
Requirement already satisfied: pyarrow>=15.0.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets==3.6.0) (23.0.1)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets==3.6.0) (0.3.8)
Requirement already satisfied: pandas in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets==3.6.0) (3.0.1)
Requirement already satisfied: requests>=2.32.2 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets==3.6.0) (2.32.5)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets==3.6.0) (4.67.3)
Requirement already satisfied: xxhash in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets==3.6.0) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets==3.6.0) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets==3.6.0) (1.4.1)
Requirement already satisfied: packaging in c:\users\admin\appdata\roaming\python\python312\site-packages (from datasets==3.6.0) (26.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from datasets==3.6.0) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.24.0->datasets==3.6.0) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.24.0->datasets==3.6.0) (0.28.1)
Requirement already satisfied: shellingham in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.24.0->datasets==3.6.0) (1.5.4)
Requirement already satisfied: typer-slim in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.24.0->datasets==3.6.0) (0.24.0)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.24.0->datasets==3.6.0) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.32.2->datasets==3.6.0) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.32.2->datasets==3.6.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.32.2->datasets==3.6.0) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.32.2->datasets==3.6.0) (2026.1.4)
Requirement already satisfied: colorama in c:\users\admin\appdata\roaming\python\python312\site-packages (from tqdm>=4.66.3->datasets==3.6.0) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pandas->datasets==3.6.0) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from pandas->datasets==3.6.0) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets==3.6.0) (1.22.0)
Requirement already satisfied: anyio in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets==3.6.0) (4.12.1)
Requirement already satisfied: httpcore==1.* in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets==3.6.0) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets==3.6.0) (0.16.0)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas->datasets==3.6.0) (1.17.0)
Requirement already satisfied: typer>=0.24.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from typer-slim->huggingface-hub>=0.24.0->datasets==3.6.0) (0.24.0)
Requirement already satisfied: click>=8.2.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.24.0->datasets==3.6.0) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.24.0->datasets==3.6.0) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.24.0->datasets==3.6.0) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.24.0->datasets==3.6.0) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.24.0->datasets==3.6.0) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.24.0->datasets==3.6.0) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import pandas as pd
import numpy as np
import torch
from datasets import load_dataset, Dataset
from transformers import (
    AutoTokenizer, 
    AutoModelForSequenceClassification, 
    TrainingArguments, 
    Trainer
)
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

c:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [9]:
dataset = load_dataset("Hello-SimpleAI/HC3", name="all")

In [10]:
data_rows = []

for item in dataset['train']:
    # Add human answers (Label 0)
    for human_ans in item['human_answers']:
        data_rows.append({'text': human_ans, 'label': 0})
        
    # Add ChatGPT answers (Label 1)
    for chatgpt_ans in item['chatgpt_answers']:
        data_rows.append({'text': chatgpt_ans, 'label': 1})

In [11]:
df = pd.DataFrame(data_rows)

In [12]:
df.head()

                                                text  label
0  Basically there are many categories of " Best ...      0
1  If you 're hearing about it , it 's because it...      0
2  One reason is lots of catagories . However , h...      0
3  There are many different best seller lists tha...      1
4  salt is good for not dying in car crashes and ...      0

In [13]:
train_df, val_df = train_test_split(df, test_size=0.2, random_state=42, stratify=df['label'])

In [14]:
train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(val_df)

In [15]:
print("Loading Tokenizer...")
model_name = "roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

Loading Tokenizer...

In [16]:
def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True, max_length=256)

In [17]:
tokenized_train = train_dataset.map(tokenize_function, batched=True)
tokenized_val = val_dataset.map(tokenize_function, batched=True)

Map: 100%|██████████| 68359/68359 [00:10<00:00, 6452.12 examples/s]
Map: 100%|██████████| 17090/17090 [00:02<00:00, 6392.40 examples/s]

In [18]:
print("Loading RoBERTa Model...")
# num_labels=2 because it's binary classification (Human vs AI)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

Loading RoBERTa Model...

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1073.49it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [19]:
import torch
print(f"Is CUDA (NVIDIA GPU) available? : {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU Name : {torch.cuda.get_device_name(0)}")

Is CUDA (NVIDIA GPU) available? : True
GPU Name : NVIDIA RTX A4000

In [20]:
# Define the device explicitly
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Active Device: {device}")

# Move the RoBERTa model to the NVIDIA GPU
model = model.to(device)

Active Device: cuda

In [21]:
def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='binary')
    acc = accuracy_score(labels, preds)
    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

In [22]:
import torch
device = torch.device("cuda")
model = model.to(device)
print(f"Model successfully moved to: {device}")

Model successfully moved to: cuda

In [23]:
%pip install "accelerate>=1.1.0"

Requirement already satisfied: accelerate>=1.1.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (1.12.0)
Requirement already satisfied: numpy>=1.17 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from accelerate>=1.1.0) (2.4.2)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from accelerate>=1.1.0) (26.0)
Requirement already satisfied: psutil in c:\users\admin\appdata\roaming\python\python312\site-packages (from accelerate>=1.1.0) (7.2.2)
Requirement already satisfied: pyyaml in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from accelerate>=1.1.0) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from accelerate>=1.1.0) (2.5.1+cu121)
Requirement already satisfied: huggingface_hub>=0.21.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from accelerate>=1.1.0) (1.4.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from accelerate>=1.1.0) (0.7.0)
Requirement already satisfied: filelock in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.28.1)
Requirement already satisfied: shellingham in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (1.5.4)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (4.67.3)
Requirement already satisfied: typer-slim in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.24.0)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from huggingface_hub>=0.21.0->accelerate>=1.1.0) (4.15.0)
Requirement already satisfied: networkx in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torch>=2.0.0->accelerate>=1.1.0) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torch>=2.0.0->accelerate>=1.1.0) (3.1.6)
Requirement already satisfied: setuptools in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torch>=2.0.0->accelerate>=1.1.0) (82.0.0)
Requirement already satisfied: sympy==1.13.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from torch>=2.0.0->accelerate>=1.1.0) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from sympy==1.13.1->torch>=2.0.0->accelerate>=1.1.0) (1.3.0)
Requirement already satisfied: anyio in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (4.12.1)
Requirement already satisfied: certifi in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (1.0.9)
Requirement already satisfied: idna in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.16.0)
Requirement already satisfied: colorama in c:\users\admin\appdata\roaming\python\python312\site-packages (from tqdm>=4.42.1->huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from jinja2->torch>=2.0.0->accelerate>=1.1.0) (3.0.3)
Requirement already satisfied: typer>=0.24.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from typer-slim->huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.24.0)
Requirement already satisfied: click>=8.2.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from typer>=0.24.0->typer-slim->huggingface_hub>=0.21.0->accelerate>=1.1.0) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from typer>=0.24.0->typer-slim->huggingface_hub>=0.21.0->accelerate>=1.1.0) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from typer>=0.24.0->typer-slim->huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface_hub>=0.21.0->accelerate>=1.1.0) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface_hub>=0.21.0->accelerate>=1.1.0) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface_hub>=0.21.0->accelerate>=1.1.0) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
# 7. Define Training Arguments (Hyperparameters + GPU Optimization)
training_args = TrainingArguments(
    output_dir="./roberta-hc3-detector",
    eval_strategy="epoch",       # <--- THIS IS THE FIX
    save_strategy="epoch",
    learning_rate=2e-5,          
    num_train_epochs=3,          
    weight_decay=0.01,
    load_best_model_at_end=True,
    logging_dir='./logs',
    
    # --- GPU & HARDWARE OPTIMIZATION SETTINGS ---
    per_device_train_batch_size=16, 
    per_device_eval_batch_size=16,
    fp16=True,                      
    dataloader_num_workers=4,       
    # --------------------------------------------
)

`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

In [25]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,
    compute_metrics=compute_metrics,
)

In [26]:
print("Starting Training...")
trainer.train()

Starting Training...

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.27it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.02it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.16it/s]
There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias', 'roberta.encoder.layer.6.attention.output.LayerNorm.weight', 'roberta.encoder.layer.6.attention.output.LayerNorm.bias', 'roberta.encoder.layer.6.output.LayerNorm.weight', 'roberta.encoder.layer.6.output.LayerNorm.bias', 'roberta.encoder.layer.7.attention.output.LayerNorm.weight', 'roberta.encoder.layer.7.attention.output.LayerNorm.bias', 'roberta.encoder.layer.7.output.LayerNorm.weight', 'roberta.encoder.layer.7.output.LayerNorm.bias', 'roberta.encoder.layer.8.attention.output.LayerNorm.weight', 'roberta.encoder.layer.8.attention.output.LayerNorm.bias', 'roberta.encoder.layer.8.output.LayerNorm.weight', 'roberta.encoder.layer.8.output.LayerNorm.bias', 'roberta.encoder.layer.9.attention.output.LayerNorm.weight', 'roberta.encoder.layer.9.attention.output.LayerNorm.bias', 'roberta.encoder.layer.9.output.LayerNorm.weight', 'roberta.encoder.layer.9.output.LayerNorm.bias', 'roberta.encoder.layer.10.attention.output.LayerNorm.weight', 'roberta.encoder.layer.10.attention.output.LayerNorm.bias', 'roberta.encoder.layer.10.output.LayerNorm.weight', 'roberta.encoder.layer.10.output.LayerNorm.bias', 'roberta.encoder.layer.11.attention.output.LayerNorm.weight', 'roberta.encoder.layer.11.attention.output.LayerNorm.bias', 'roberta.encoder.layer.11.output.LayerNorm.weight', 'roberta.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.beta', 'roberta.embeddings.LayerNorm.gamma', 'roberta.encoder.layer.0.attention.output.LayerNorm.beta', 'roberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.0.output.LayerNorm.beta', 'roberta.encoder.layer.0.output.LayerNorm.gamma', 'roberta.encoder.layer.1.attention.output.LayerNorm.beta', 'roberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.1.output.LayerNorm.beta', 'roberta.encoder.layer.1.output.LayerNorm.gamma', 'roberta.encoder.layer.2.attention.output.LayerNorm.beta', 'roberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.2.output.LayerNorm.beta', 'roberta.encoder.layer.2.output.LayerNorm.gamma', 'roberta.encoder.layer.3.attention.output.LayerNorm.beta', 'roberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.3.output.LayerNorm.beta', 'roberta.encoder.layer.3.output.LayerNorm.gamma', 'roberta.encoder.layer.4.attention.output.LayerNorm.beta', 'roberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.4.output.LayerNorm.beta', 'roberta.encoder.layer.4.output.LayerNorm.gamma', 'roberta.encoder.layer.5.attention.output.LayerNorm.beta', 'roberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.5.output.LayerNorm.beta', 'roberta.encoder.layer.5.output.LayerNorm.gamma', 'roberta.encoder.layer.6.attention.output.LayerNorm.beta', 'roberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.6.output.LayerNorm.beta', 'roberta.encoder.layer.6.output.LayerNorm.gamma', 'roberta.encoder.layer.7.attention.output.LayerNorm.beta', 'roberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.7.output.LayerNorm.beta', 'roberta.encoder.layer.7.output.LayerNorm.gamma', 'roberta.encoder.layer.8.attention.output.LayerNorm.beta', 'roberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.8.output.LayerNorm.beta', 'roberta.encoder.layer.8.output.LayerNorm.gamma', 'roberta.encoder.layer.9.attention.output.LayerNorm.beta', 'roberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.9.output.LayerNorm.beta', 'roberta.encoder.layer.9.output.LayerNorm.gamma', 'roberta.encoder.layer.10.attention.output.LayerNorm.beta', 'roberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.10.output.LayerNorm.beta', 'roberta.encoder.layer.10.output.LayerNorm.gamma', 'roberta.encoder.layer.11.attention.output.LayerNorm.beta', 'roberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.11.output.LayerNorm.beta', 'roberta.encoder.layer.11.output.LayerNorm.gamma'].

TrainOutput(global_step=12819, training_loss=0.007996558404924792, metrics={'train_runtime': 1744.8929, 'train_samples_per_second': 117.53, 'train_steps_per_second': 7.347, 'total_flos': 2.697901295003136e+16, 'train_loss': 0.007996558404924792, 'epoch': 3.0})

In [27]:
trainer.save_model("./final-roberta-hc3")
tokenizer.save_pretrained("./final-roberta-hc3")
print("Training Complete and Model Saved!")

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.83it/s]

Training Complete and Model Saved!